<?php

/**
 * @file
 * Main functions and hook implementations of the RDF Entity Test module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_install
 */
function triplestore_indexer_test_install() {
    \Drupal::configFactory()->getEditable('rest.resource.entity.file')->delete();
    \Drupal::configFactory()->getEditable('rest.resource.entity.media')->delete();
    \Drupal::configFactory()->getEditable('rest.resource.entity.node')->delete();
    \Drupal::configFactory()->getEditable('rest.resource.entity.taxonomy_term')->delete();
}

/**
 * Implements hook_entity_base_field_info().
 */
function triplestore_indexer_test_entity_base_field_info(EntityTypeInterface $entity_type)
{

    if (\Drupal::moduleHandler()->moduleExists('jsonld')
        || \Drupal::moduleHandler()->moduleExists('rest')
        || \Drupal::moduleHandler()->moduleExists('restui')
        || \Drupal::moduleHandler()->moduleExists('advancedqueue')
    ) {
        return;
    }
}